#!/bin/bash
set -e
umask 2

KSRC=~/Linux-src/linux

suf=custom
T=/tmp/linux-$suf
mkdir "$T"
cp -var ~/projects/aur/linux-custom/* "$T/"

cd "$KSRC"
tag=$(git describe --abbrev=0 -- "$@")	# v3.7-rc3
tagrev=$(git describe -- "$@")		# v3.7-rc3-1-gxxxx
basekernel=${tag#v}		# 3.7-rc3
basekernel=${basekernel%%-*}	# 3.7
pkgver=${tagrev#v}		# 3.7-rc3-1-gxxxx
if [[ $pkgver == $basekernel-* ]]; then
	pkgver=${pkgver#$basekernel-}	# rc3-1-gxxxx
	pkgver=${pkgver//-/_}		# rc3_1_gxxxx
else
	pkgver=
fi

git archive --prefix="linux-$basekernel/" --format=tar.gz \
	-o "$T/linux-$basekernel.tar.gz" -- "$tagrev"

cd "$T"
sed -i PKGBUILD \
	-e "s/^_basekernel=.*/_basekernel=$basekernel/" \
	-e "s/^pkgver=.*/pkgver=\${_basekernel}$pkgver/"
