#!/bin/bash
set -e
umask 22

KSRC=~/Linux-src/linux

suf=custom
T=/tmp/linux-$suf
mkdir "$T"
cp -var ~/projects/aur/linux-custom/* "$T/"

cd "$KSRC"
tag=$(git describe --abbrev=0 -- "$@")	# v3.7-rc3		v3.12
tagrev=$(git describe -- "$@")		# v3.7-rc3-1-gxxxx	v3.12-1-gxxxx
basekernel=${tag#v}			# 3.7-rc3		3.12
if [[ $tag != $tagrev ]]; then
	# v3.7-rc3-1-gxxxx -> -00001-gxxxx
	scmversion=$(echo "$tagrev" | awk -F- '{printf("-%05d-%s", $(NF-1),$(NF))}')
else
	scmversion=
fi

git archive --prefix="linux-$basekernel/" --format=tar.gz \
	-o "$T/linux-$basekernel.tar.gz" -- "$tagrev"

cd "$T"
sed -i PKGBUILD \
	-e "s/^_basekernel=.*/_basekernel=$basekernel/" \
	-e "s/^_scmversion=.*/_scmversion=$scmversion/"
#	-e "s/^pkgver=.*/pkgver=\${_basekernel}$pkgver/"
